version: '3'

services:
  config-service:
    image: spring17/config-service
    #hostname: config-service
    #volumes:
    #  - ./config-service/config:/app/config
    ports:
      - "8088:8088"
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/config-service
        awslogs-region: ap-east-1
        awslogs-stream-prefix: web

  discovery-service:
    image:  spring17/discovery-service
    #hostname: discovery-service
    #links:
    #  - "config-service"
    ports:
      - "8061:8061"
    logging:
      driver: awslogs
      options: 
        awslogs-group: /ecs/discovery-service
        awslogs-region: ap-east-1
        awslogs-stream-prefix: web