spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"
---
spring:
  config:
    activate:
      on-profile: docker
    import: "optional:configserver:http://config-service:8088"