server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: services.organization

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8020
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/